### PR TITLE
Support table alias when using metable join

### PR DESCRIPTION
**Pull request by lrfahmi**

### CODE REVIEW

**Comment by paschaldev** [comment]
Nice. I wrote something similar and was about to send a pull request. Glad you already did.

**Comment by paschaldev** [comment]
@kodeine Do check this out.

**Comment by dhcmega** [comment]
Hi
This is breaking my apps.
Query is generated as:
```
select `users`.* from `users` inner join `users_meta` as `meta` on `users`.`id` = `meta`.`user_id` where (`users_meta`.`key` = lot and `users_meta`.`value` is null and `users_meta`.`user_id` <> 1) and `users`.`deleted_at` is null and `users`.`account_id` >= 0
```

users is aliased as `meta` but later used as `users_meta`, which gives error

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users_meta.key' in 'where clause' (SQL: select `users`.* from `users` inner join `users_meta` as `meta` on `users`.`id` = `meta`.`user_id` where (`users_meta`.`key` = lot and `users_meta`.`value` is null and `users_meta`.`user_id` <> 1) and `users`.`deleted_at` is null and `users`.`account_id` >= 0) (View: /home/vpssigesedev/sigesedev.huayra.com.ar/resources/views/admin/users/show_fields.blade.php) (View: /home/vpssigesedev/sigesedev.huayra.com.ar/resources/views/admin/users/show_fields.blade.php)
```

**Comment by paschaldev** [comment]
@dhcmega You're aliasing as `meta` so you query should look like this 

```php 
return self::meta()
            ->where(function($query){
                $query->where('meta.key', '=', 'lot')
                    ->where('meta.value', '=', $this->lot)
                    ->where('meta.user_id', '<>', $this->id);
            })->get();
```

However if you'll like to keep using your `users_meta` alias, you have to pass it as the first argument to `meta()`

```php
        return self::meta('users_meta')
            ->where(function($query){
                $query->where('users_meta.key', '=', 'lot')
                    ->where('users_meta.value', '=', $this->lot)
                    ->where('users_meta.user_id', '<>', $this->id);
            })->get();
```

**Comment by dhcmega** [comment]
Hi @paschaldev , thanks for your answer.
I understand that both ways are valid for this case. What I mean is that this modification to the method breaks the code unless I go to all the places I used it and modify the code.
I think this kind of modifications should be introduced without breaking the code, so users can update without having to search all around the code to fix every use of this method.
Thanks.

**Comment by paschaldev** [comment]
@dhcmega Well, true you have a point. I personally had to replace every file that uses meta. Everything works fine. 

However it is not a good idea to leave it blank especially if you're working with many `joins`. It is usually a good idea to give your joins an alias so you don't get unexpected results.

**Comment by dhcmega** [comment]
@paschaldev I know, but:

```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```
If it's not a major upgrade, like going from v1 to v2, it cannot break things.
Thanks!

**Comment by kodeine** [comment]
can anyone submit a PR for the fix or settings the default? Im on vacation so wont be able to test it out

**Comment by dhcmega** [comment]
@kodeine I have never created a PR. I can check the code and propose a possible solution if that helps.

**Comment by paschaldev** [comment]
@dhcmega I'll create a PR request for that. Exactly like that

**Comment by dhcmega** [comment]
@paschaldev I have tested it and worked for me. Have you tested it yourself? Just in case. Thanks again.

**Comment by lrfahmi** [comment]
The `$alias` parameter here serves to filter out some meta keys. For example: I want to display **BLOG_POST** which has `key='category'` and `value='food'`, also `key='active'` and `value='true'`. Then the query used like this:

```
$blog_posts = BlogPost::select();
$blog_posts = $blog_posts->meta('fk_1')->where(function($query) {
                    $query->where('fk_1.key', '=', 'category')
                          ->where('fk_1.value', '=', 'food');
                });
				
$blog_posts = $blog_posts->meta('fk_2')->where(function($query) {
                    $query->where('fk_2.key', '=', 'active')
                          ->where('fk_2.value', '=', 'true');
                });
				
$blog_posts = $blog_posts->distinct();
$blog_posts = $blog_posts->get();
```
Notes: Alias FK_ (Filter Key) **fk_1 is to filter category** and **fk_2 is to filter active status**.

If you do not want to use this function, use a default query like this:

```
$blog_posts = BlogPost::select();
$blog_posts = $blog_posts->meta()->where(function($query) {
                    $query->where('meta.key', '=', 'category')
                          ->where('meta.value', '=', 'food');

$blog_posts = $blog_posts->get();
```

Hope it helps and correction if there are errors. Thanks.

**Comment by kodeine** [comment]
@lrfahmi can we use default alias so its backwards compatible?

**Comment by lrfahmi** [comment]
Thanks to all. @kodeine @paschaldev  @dhcmega now it's backwards compatible.

**Comment by kodeine** [comment]
Thank you @lrfahmi and all.

**Comment by dhcmega** [comment]
Great, thanks!!

**Pull request merged**
