### PR TITLE
[2.0] laravel meta vesion 2

### LINKED ISSUE #10: Support for 4.2 dropped?
Hey there

The recent update removed laravel 4.2 support, is there a change in the code that requires laravel 5.0/5.1? From what I can see, there doesn't seem to a reason to exclude 4.2, but I may be mistaken.

### LINKED ISSUE #17: Meta is always fetch from database
Hello!

For example: I have a list of 10 movies and these movies have some metas. So, when a get all these movies, I have notice that 10 queries where executed to get all metas for each movie. 
In a situation where I don't need these metas, I have this queries in the same way.

So, is there any way to not get all that data automatically? Cause I have a situation where I count some data and I don't need any meta. I'm thinking about it cause for each new data in the database, a new query will be executed later. See the image below:

log

Any help? Thanks!

### LINKED ISSUE #18: Different types
I realized that even though we created a meta da as Integer, the database appears as String.
I do not think a problem, but you think about upgrading?

### LINKED ISSUE #21: `getMeta` function parameter
Hi ,
In the readme it states the `getMeta` function accept meta key params and default value.

```
$post = $post->getMeta('content', 'Something');
```

But on the code i check that the params is `key` and `raw`, is this the intended behaviour ?  using `raw` = `true` will return the meta as json

### LINKED ISSUE #22: scopeMeta doesn't work with tables with custom names
Hello guys!

See scopeMeta

```
public function scopeMeta($query)
    {
        return $query->join($this->table.'_meta', $this->table.'.id', '=', $this->table.'_meta.'.$this->getMetaKeyName())
            ->select($this->table.'.*');
    }
```

**$this->table.'_meta'** will assume that your meta table has "**meta**" in the name. In my case, my table is called "users_data", then this method will fail. 

I just rewrite the function in my model and it's working fine now but I think that it should be fixed to work with tables that doesn't follow that pattern.

I'm posting this issue cause this package allow us to define a custom name for our meta tables.

See you! :)

### LINKED ISSUE #38: Unnecessary where clause on collection
I think this where can be removed because the relationship method already gets model specific meta.
I get problem with that where because depending on the environment returned collection fields which must be int (e.g foreign key) are casted to string and this where returns null.

https://github.com/kodeine/laravel-meta/blob/70d02d9f5adc5422738bba8b1955e0f4c597d1ab/src/Kodeine/Metable/Metable.php#L214-L233 

https://github.com/laravel/framework/issues/11780

### LINKED ISSUE #40: Can't retrieve with eager loading
Hi guys,

I'm trying to use the eager load in my laravel project. I have a Term table with his meta table.
When i do this :  

`$terms = Term::with(['metas'])->get();`

I have an error which is saying that the relationship "metas" doesn't exist. Which is true because i dont have a function "metas" in my model. But i don't know what to put inside this function "metas". 

Can you help me ?
Thanks

### LINKED ISSUE #44: Option to disable assignment statement that triggers multiple column checks
The issue is It checks the the model's table column  everytime we assign a model property value. 

Can we have an option to disable this feature and just rely on the setMeta function?

### LINKED ISSUE #47: Could not name meta values beginning with "meta"
Hi,

I recently figured out that the package refuses storing meta beginning with `meta`. It looks that it resolve problematic internal variables saving (https://github.com/kodeine/laravel-meta/blob/master/src/Kodeine/Metable/Metable.php#L339).

But it as this package allows fluent declaration, it could be interesting to allows the `meta` prefix (example : `$model->meta_my_variable`). I allows us to differenciate meta and non meta values.

### LINKED ISSUE #49: whereMeta should be static
Hi!
I think whereMeta should be static, so you can do something like:

`
$posts = Post::whereMeta($key, $value);
`

```
    /**
     * Query Meta Table functions
     * -------------------------.
     */
    public function whereMeta($key, $value)
    {
        return $this->getModelStub()
            ->whereKey(strtolower($key))
            ->whereValue($value)
            ->get();
    }
```

Thanks!

### PR DESCRIPTION
**Pull request by siamak2**
There are a lot of backward incompatible features were added. you can read about them in `README.md`.
Also changes mentioned in CHANGELOG.md
This PR also fix some of the issues:
fixed https://github.com/kodeine/laravel-meta/issues/89
fixed https://github.com/kodeine/laravel-meta/issues/83
fixed https://github.com/kodeine/laravel-meta/issues/71
fixed https://github.com/kodeine/laravel-meta/issues/70
closes https://github.com/kodeine/laravel-meta/issues/63
fixed https://github.com/kodeine/laravel-meta/issues/59
closes https://github.com/kodeine/laravel-meta/issues/54
fixed https://github.com/kodeine/laravel-meta/issues/49
fixed https://github.com/kodeine/laravel-meta/issues/47
fixed https://github.com/kodeine/laravel-meta/issues/44
fixed https://github.com/kodeine/laravel-meta/issues/40
fixed https://github.com/kodeine/laravel-meta/issues/38
fixed https://github.com/kodeine/laravel-meta/issues/22
fixed https://github.com/kodeine/laravel-meta/issues/21
closes https://github.com/kodeine/laravel-meta/issues/18
closes https://github.com/kodeine/laravel-meta/issues/17 (it was fixed before)
close https://github.com/kodeine/laravel-meta/issues/10 (it's a very old issue and laravel doesn't support 4.2 either)

### CODE REVIEW

**Comment by siamak2** [comment]
@kodeine 
make sure you release 2.0.0 version and also make sure packagist picks up the changes.
don't forget setting branch `2.0` as default
becasuse my IDE changed indent github's diff doesn't show actual diff for `Matable.php`
I commited indent changes separately. you can view actual changes in this diff:
[actual diff](https://github.com/siamak2/laravel-meta/compare/7ae8c78c0396b4f21195dca5cbbb5764666c1dd2...2.x#diff-571db7870bfc167374797b5b0093dee8a22f29dee7ea6465d4f5a3d91334df2c)

**Comment by kodeine** [comment]
Perfect, thanks a lot!

**Comment by siamak2** [comment]
Github didn't auto close issues I mentioned (I geuss because branch `2.0` was not default when you merged it).
Can you manually close them?

**Comment by kodeine** [comment]
@siamak2 done

**Pull request merged**
