### PR TITLE
Implement Default Values with Model Variable

### PR DESCRIPTION
**Pull request by benyanke**
Implements #45. 

I'd love to see your thoughts on this.

Sorry for the additional diff lines, my IDE was doing a bit too much for me. Can clean that up, if you're strict about formatting.

### CODE REVIEW

**Comment by benyanke** [comment]
Hey - just following up on this. What are your thoughts on this PR?

**Comment by benyanke** [comment]
Hi @kodeine - have you been able to give any thought to this?

**Comment by bobmulder** [comment]
I'd like to see this PR merged... Any reason why this hasn't been done yet, @kodeine?

**Comment by kodeine** [comment]
@benyanke i would love to have this feature, i'm sorry for the late response, would you please mind fixing the formatting and i'll merge this right away! Thank you!

**Comment by benyanke** [comment]
Fixed - conflict was just some formatting, not a real conflict.

**Comment by kodeine** [comment]
@benyanke Thank you!

**Comment by tnorthcutt** [comment]
Is there a way to take advantage of default values when using this via the query builder?

e.g. I have an `scopeUpgradeable()` method on my model which looks like this (simplified):

```
public function scopeUpgradeable($query)
{
    return $query->where('is_active', true)
        ->where(function ($q) {
            $q->where('accounts_meta.key', '=', 'dont_upgrade')
              ->where('accounts_meta.value', '=', false);
        });
}
```

But since not all Accounts have the `dont_upgrade` meta key present (99% do not have it set), this query doesn't really work.

**Pull request merged**
