### PR TITLE
Update MetaData.php

### PR DESCRIPTION
**Pull request by ricardomartos**
change connection name if env 'METADATA_DATABASE' is set

### CODE REVIEW

**Comment by kodeine** [comment]
Please update the readme as well to reflect the addition of env variable

**Comment by ricardomartos** [comment]
@kodeine I think is ready know ;)

**Comment by ricardomartos** [comment]
If you are using this package with a secondary database connection, you can set the `METADATA_DATABASE` variable in your `.env`in order to let this package know the secondary connection database name.```// CONNECTION #1DB_CONNECTION=mysqlDB_HOST=127.0.0.1DB_PORT=3306DB_DATABASE=&lt;NAME&gt;DB_USERNAME=&lt;USERNAME&gt;DB_PASSWORD=&lt;PASSWORD&gt;// CONNECTION #2DB_CONNECTION=mysqlDB_HOST=&lt;SOME_OTHER_HOST&gt;DB_PORT=3306DB_DATABASE=&lt;NAME&gt; &lt;--DB_USERNAME=&lt;USERNAME&gt;DB_PASSWORD=&lt;PASSWORD&gt;METADATA_DATABASE=&lt;NAME&gt; &lt;--

**Comment by siamak2** [comment]
This PR has two major problems:

1. you really shouldn't use `env` outside of `config` directory as explained in Laravel's [documention](https://laravel.com/docs/9.x/configuration#configuration-caching)
2. Laravel relations won't work between two connections

**Pull request closed without merging**
