### PR TITLE
Upgrade composer.json to be used with Laravel 8

### PR DESCRIPTION
**Pull request by Sebteams69**
Just updated composer.json to support Laravel 8

### CODE REVIEW

**Review by JonathanMurre — APPROVED** [review]
Hope this will be merged quickly!

**Comment by kodeine** [comment]
Thank you

**Comment by JonathanMurre** [comment]
Great! Could you add a tag so it will work with composer?

**Comment by kodeine** [comment]
@JonathanMurre Just added a tag.

**Pull request merged**
