### PR TITLE
fix hascolmn check @ metable.php

### PR DESCRIPTION
**Pull request by ray1618**
Uncommented lines 326 -> 329 to re-enable HasColmn check, no fancy stuff

### CODE REVIEW

**Comment by blackburn1911** [comment]
I will test right now

**Comment by blackburn1911** [comment]
Now you can add metas in same instance because I have not tested yet.

**Comment by ray1618** [comment]
yes and the models own attributes

**Comment by kodeine** [comment]
@ray1618 @blackburn1911 
You guys can help write tests for this package?

**Comment by ray1618** [comment]
@kodeine Not sure if I can be much help, I'm quite new to Laravel..

**Comment by kodeine** [comment]
@ray1618, no problem :)

**Pull request merged**
